/**
 * POST /api/messages/ingest
 * Ingest endpoint - parse, store, and broadcast messages
 * Node runtime (needs storage and SSE)
 */

import { NextRequest, NextResponse } from 'next/server';
import { parseStrict } from '@/lib/fix/strict';
import { generateRepairSuggestions } from '@/lib/fix/repair';
import { getStore } from '@/lib/store';
import { checkAuth } from '@/lib/server/auth';
import { getCorsHeaders, handleCorsPreFlight } from '@/lib/server/cors';
import { checkRateLimit, RATE_LIMITS } from '@/lib/server/ratelimit';
import type { FixMessage } from '@/lib/types';

export const runtime = 'nodejs';

export async function OPTIONS(request: NextRequest) {
  return handleCorsPreFlight(request);
}

export async function POST(request: NextRequest) {
  // Check rate limit (write endpoint)
  const rateLimitError = checkRateLimit(request, RATE_LIMITS.write);
  if (rateLimitError) {
    return rateLimitError;
  }

  // Check authentication
  const authError = checkAuth(request);
  if (authError) {
    return authError;
  }

  try {
    // Get raw message from request body
    const contentType = request.headers.get('content-type') || '';
    let rawMessage: string;

    if (contentType.includes('application/json')) {
      const body = await request.json();
      rawMessage = body.message || body.rawMessage || '';
    } else {
      // Default to text/plain
      rawMessage = await request.text();
    }

    if (!rawMessage || rawMessage.trim() === '') {
      return NextResponse.json(
        {
          error: 'Missing message body',
        },
        {
          status: 400,
          headers: getCorsHeaders(request),
        }
      );
    }

    // Parse with strict parser
    const parseResult = parseStrict(rawMessage);

    if (!parseResult.success) {
      // Parse failed - return issues and suggestions
      const suggestions = generateRepairSuggestions(
        rawMessage,
        parseResult.issues
      );

      return NextResponse.json(
        {
          error: parseResult.error,
          issues: parseResult.issues,
          suggestions,
        },
        {
          status: 400,
          headers: getCorsHeaders(request),
        }
      );
    }

    const parsed = parseResult.message;

    // Create message object for storage
    const message: FixMessage = {
      id: '', // Will be generated by store
      rawMessage,
      fields: parsed.fields,
      summary: parsed.summary,
      warnings: parsed.warnings,
    };

    // Store message
    const store = getStore();
    const storedMessage = await store.add(message);

    // Message will be automatically broadcasted via SSE by the store

    return NextResponse.json(
      {
        data: storedMessage,
      },
      {
        status: 201,
        headers: getCorsHeaders(request),
      }
    );
  } catch (error) {
    console.error('Ingest endpoint error:', error);
    return NextResponse.json(
      {
        error: 'Internal server error',
      },
      {
        status: 500,
        headers: getCorsHeaders(request),
      }
    );
  }
}
